name: flutter_template
description: Boilarplate template of Flutter GetX.
publish_to: none
version: 0.0.1+1
environment: 
  sdk: '>=3.1.0 <4.0.0'

scripts:
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  launch:
    dev: flutter run --flavor dev --dart-define=flavor=dev
    stg: flutter run --flavor stg --dart-define=flavor=stg
    prod: flutter run --flavor prod --dart-define=flavor=prod
  build:
    apk:
      dev: flutter build apk --flavor=dev --dart-define=flavor=dev --debug
      stg: flutter build apk --flavor=stg --dart-define=flavor=stg --debug
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --debug
    release-apk:
      dev: flutter build apk --flavor=dev --dart-define=flavor=dev --release --obfuscate --split-debug-info=debug-info
      stg: flutter build apk --flavor=stg --dart-define=flavor=stg --release --obfuscate --split-debug-info=debug-info
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --release --obfuscate --split-debug-info=debug-info
    appbundle:
      dev: flutter build appbundle --flavor=dev --dart-define=flavor=dev
      stg: flutter build appbundle --flavor=stg --dart-define=flavor=stg
      prod: flutter build appbundle --flavor=prod --dart-define=flavor=prod
    ios:
      dev: flutter build ios --flavor=dev --dart-define=flavor=dev --debug --no-codesign
      stg: flutter build ios --flavor=stg --dart-define=flavor=stg --debug --no-codesign
      prod: flutter build ios --flavor=prod --dart-define=flavor=prod --debug --no-codesign

dependencies:
  flutter: 
    sdk: flutter
  animations: ^2.0.8
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_localizations: 
    sdk: flutter
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.8
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  intl: ^0.19.0
  json_serializable: ^6.7.1
  logger: ^1.4.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

  #* Firebase
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.4.6

dev_dependencies: 
  analyzer: ^5.13.0
  build_runner: ^2.4.6
  dart_code_metrics: any
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - .env
    - .env.dev
    - .env.stg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic
